apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: upload-page
  name: upload-page
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: upload-page
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: upload-page
    spec:
      containers:
        - image: unstable-upload-page
          imagePullPolicy: Never
          name: upload-page
          ports:
            - containerPort: 4000
              protocol: TCP
          volumeMounts:
            - mountPath: /src
              name: upload-page-claim0
      restartPolicy: Always
      volumes:
        - name: upload-page-claim0
          persistentVolumeClaim:
            claimName: upload-page-claim0
